---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
  namespace: app1
data:
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  FRONTEND_URL: "http://app1-frontend"
  DATABASE_HOST: "postgres-primary"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "app1"
